client_id = YOUR_CLIENT_ID
client_secret = YOUR_CLIENT_SECRET
refresh_interval_minute = 60
session_duration_minute = 30
default_timeout_millisecond = 10000
tracking_interval_millisecond = 1000
top_level_domain = ".domain.com"
environment = "production"
